make sure to use GNU Make

diff --git a/script/xlate b/script/xlate
--- a/script/xlate
+++ b/script/xlate
@@ -373,6 +373,16 @@ do
 done	
 shift $((OPTIND - 1))
 
+find_gmake() {
+    local make
+    (( $# == 0 )) && set make gmake gnumake
+    for make in $@
+    do
+	[[ $($make --version) =~ GNU ]] && { echo $make; return 0; }
+    done
+    return 1
+}
+
 ##
 ## Make
 ##
@@ -391,7 +401,8 @@ then
 	fi
     done
     unset MAKELEVEL
-    exec make -f $share/XLATE.mk \
+    gmake=$(find_gmake) || { warn "GNU Make is required."; exit 1; }
+    exec $gmake -f $share/XLATE.mk \
 	 ${dryrun:+-n} \
 	 XLATE_LANG=\""$tgt_lang"\" \
 	 XLATE_DEBUG=$debug \
@@ -407,7 +418,7 @@ fi
 
 if [[ ! $tgt_lang ]]
 then
-    warn "-t option is required."
+    warn "$myname: -t option is required."
     exit 1
 fi
 
